install.packages("shinydashboardPlus")
install.packages("ggplot2")
install.packages("shiny")
install.packages("datasets")
install.packages("testthat")
install.packages("shinyjs")
install.packages("shinyWidgets")
install.packages("scales")
